sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: galgamesaya

  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5t6aToFz3aRiWKLEBhYg
    access-key-secret: Dzk0bAZeiGkTkgUcyaXmFEpHrIkJAL
    bucket-name: tlias-learn-2
